.github/workflows/repository.yml

See https://github.com/goto/charts/pull/3#issuecomment-1469794544

ci: don't run release for PRs

---

stable/meteor/Chart.yaml
stable/meteor/README.md
stable/meteor/values.yaml

v0.8.0 is the first image published for gotocompany/meteor.

fix(meteor): use gotocompany meteor image v0.8.0

---

stable/firehose/templates/deployment.yaml
stable/firehose/values.yaml

nest volumeMount under firehose object

fix: nest volumeMount under firehose object

---

stable/firehose/templates/deployment.yaml
stable/firehose/values.yaml

nest a secret under a `secret` key

fix: nest under secret key

---

stable/app/Chart.yaml
stable/app/templates/deployment.yaml
stable/app/values.yaml

This PR should allow addition of deployment labels from values.yaml.

feat(app): add custom labels

---

stable/app/Chart.yaml
stable/app/templates/cron.yaml
stable/app/templates/migration-job.yaml

This PR should allow addition of labels from values.yaml to cron and migration-job.

feat(app): add custom labels to cron and migration-job

---

stable/firehose/Chart.yaml
stable/firehose/values.yaml

by default set below firehose configs
```
METRIC_STATSD_HOST: localhost
METRIC_STATSD_PORT: 8125
```

feat(firehose): set metrics config

---

stable/firehose/values.yaml

ConfigMap data accepts only string values

fix: change METRIC_STATSD_PORT to string

---

stable/siren/Chart.yaml
stable/siren/values.yaml

- Support multiple port for http and grpc
- Support external plugin

feat(siren): support plugin and multiple ports

---

stable/meteor/Chart.yaml
stable/meteor/templates/cronjob.yaml
stable/meteor/templates/otelcollector-configmap.yaml
stable/meteor/values.yaml

- add otelcollector configuration in meteor chart

feat: add otelcollector support for meteor

---

stable/firehose/Chart.yaml
stable/firehose/values.yaml

Setting default limits and resources

feat: add default limits & resources

---

stable/app/Chart.yaml
stable/app/templates/deployment.yaml
stable/app/values.yaml

Support optional iap sidecar in app chart

feat: support iap sidecar in app chart

---

stable/firehose/Chart.yaml
stable/firehose/values.yaml

Update default telegraf resources to:
```
Cpu:
req 70m, limit 500m
Memory
req 100Mi, limit 1000Mi
```

feat: update default telegraf resources

---

stable/app/Chart.yaml
stable/app/templates/ingress.yaml
stable/app/values.yaml
stable/compass/Chart.yaml

Support to have additional ingress to have different annotations for example between grpc and http

feat(app): support additional ingress

---

stable/app/Chart.yaml
stable/app/templates/deployment.yaml

- make resources in all sidecars in app chart configurable

feat: configurable resources on sidecar app chart

---

stable/optimus/Chart.yaml
stable/optimus/templates/deployment.yaml

This PR to address the case where the labels are not applied to the pod, as the way the labels are being specified is through label selector.

fix(optimus): add labels to pod template

---

stable/app/Chart.yaml
stable/app/templates/cron.yaml
stable/app/templates/deployment.yaml
stable/app/templates/service.yaml
stable/app/values.yaml

The deployment and service jobs were getting created for the cron job, added conditional logic to disable creating these jobs

fix(app): conditionally disable deployment app chart for cron jobs

---

stable/guardian/Chart.yaml
stable/guardian/values.yaml

Bump version and remove slack config

chore(guardian): remove slack config and bump version

---

stable/meteor/Chart.yaml
stable/meteor/templates/cronjob.yaml
stable/meteor/values.yaml
stable/optimus/Chart.yaml

**Goal:**
Hit Delete Assets by Query Expr API from Compass, to delete stales assets. The config will be imported from Terraform.

feat: set post curl command after meteor ran successfully

---

stable/entropy/Chart.yaml
stable/entropy/values.yaml

add `entropy worker` to entropy helm chart.

feat(entropy): add worker deployment

---

stable/entropy/Chart.yaml

fix entropy chart dependency name.

fix(entropy): chart dependency

---

stable/dagger/Chart.yaml

feat: add type 

---

stable/dagger/Chart.yaml
stable/dagger/templates/dagger.yaml

feat: add dagger annotations

---

stable/dagger/Chart.yaml
stable/dagger/templates/dagger.yaml

feat: add namespace to metadata

---

stable/dagger/Chart.yaml
stable/dagger/templates/dagger.yaml

remove unnecessary annotations

chore: remove annotations

---

stable/dagger/Chart.yaml
stable/dagger/templates/dagger.yaml

feat: change mode to savepoint

---

stable/metabase/templates/service.yaml

Add service template to metabase chart.

fix(metabase): add service template

---

stable/metabase/Chart.yaml
stable/metabase/templates/deployment.yaml

Fix deployment template syntax error.

fix(metabase): template

---

stable/entropy/Chart.yaml

upgrade entropy chart to version 0.7.0 app version

feat: upgrade entropy chart app version

---

stable/firehose/Chart.yaml
stable/firehose/templates/deployment.yaml

force toleration value to be string

fix: force toleration value to be string

---

stable/firehose/Chart.yaml
stable/firehose/values.yaml

Updated cpu resource requests for firehose telegraf container from 200m to 50m

fix: update cpu resource requests for firehose telegraf container

---

stable/firehose/Chart.yaml
stable/firehose/templates/keda-scaledobject.yaml
stable/firehose/values.yaml

feat(firehose): enable keda autoscaler

---

stable/firehose/Chart.yaml
stable/firehose/templates/keda-scaledobject.yaml
stable/firehose/values.yaml

fix firehose keda autoscaler templating

fix(firehose): keda autoscaler template

---

stable/firehose/templates/keda-scaledobject.yaml

- force annotation as string
- fix authenticationRef default value

fix(firehose): scaledobject config
